import { ProfileData, ProjectData, SkillData, ExperienceData, EducationData } from '@/types';

export const INITIAL_PROFILE: ProfileData = {
  id: 'profile-1',
  name: 'Lakviru Perera',
  primaryTitle: 'Software Engineer',
  heroSubtitle: 'Building scalable software, modern web applications, and practical solutions using modern technologies.',
  bio: 'Software Engineer specializing in modern web applications, backend services, and cloud technologies. Currently pursuing a BSc (Hons) in Information Technology specializing in Software Engineering at SLIIT.',
  location: 'Piliyandala, Sri Lanka',
  email: 'dinuwaperera123@gmail.com',
  githubUrl: 'https://github.com/dinuwa2500',
  linkedinUrl: 'https://www.linkedin.com/in/lakviru-perera-006050371/',
  resumeUrl: '/resume.pdf',
  avatarUrl: 'https://res.cloudinary.com/dinuwapvt/image/upload/v1761730890/31015_viq64m.jpg',
  isAvailableForWork: true,
  updatedAt: new Date().toISOString(),
};

export const INITIAL_PROJECTS: ProjectData[] = [
  {
    id: 'proj-1',
    slug: 'distributed-event-streaming-engine',
    githubRepoId: 80102144,
    githubName: 'distributed-event-engine',
    githubFullName: 'lakviruperera/distributed-event-engine',
    githubUrl: 'https://github.com/lakviruperera/distributed-event-engine',
    githubDescription: 'High-throughput distributed event streaming and task execution engine with partition balancing, persistent write-ahead logs, and sub-millisecond dispatch.',
    githubStars: 142,
    githubForks: 28,
    githubLanguage: 'TypeScript',
    githubLanguages: ['TypeScript', 'Go', 'Rust', 'Docker'],
    githubTopics: ['distributed-systems', 'event-driven', 'concurrency', 'high-throughput', 'typescript', 'microservices'],
    githubReadme: `# Distributed Event Streaming Engine\n\nA low-latency distributed event streaming broker designed for high-concurrency event ingestion, reliable replication, and parallel partition consumer groups.`,
    githubCreatedAt: '2024-03-10T10:00:00Z',
    githubUpdatedAt: '2025-01-15T18:30:00Z',
    customTitle: 'Distributed Event Streaming Engine',
    customDescription: 'A production-ready distributed event streaming system built to handle over 100,000 events/sec with guaranteed at-least-once delivery, partition balancing, and persistent append-only logs.',
    category: 'Backend',
    status: 'FEATURED',
    isFeatured: true,
    isVisible: true,
    displayOrder: 1,
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    screenshots: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80'
    ],
    problem: 'Traditional single-node message queues bottlenecked under intense spiky traffic bursts, experiencing thread contention and unrecoverable message loss during network partitions.',
    solution: 'Designed an append-only commit log architecture with zero-copy network streaming, dynamic partition leader election via Raft consensus, and configurable consumer group rebalancing.',
    myRole: 'Lead Systems Architect & Developer — Designed the consensus protocol, implemented zero-copy I/O socket pipelines, and built benchmarking suites verifying throughput under synthetic loads.',
    features: [
      'Append-only disk-backed segment storage with configurable retention policies',
      'Dynamic partition rebalancing with automatic dead-letter queue routing',
      'Sub-millisecond P99 latency dispatch under 100k events/sec',
      'Built-in cluster metrics exporter for Prometheus & Grafana telemetry'
    ],
    demoUrl: 'https://event-engine-demo.lakviru.dev',
    architecture: 'Client SDKs → TCP Gateway Load Balancer → Raft Leader Broker Node → Segmented Log Store & Replication Stream → Consumer Worker Group',
    technologies: ['TypeScript', 'Node.js', 'PostgreSQL', 'Redis', 'Docker', 'Prometheus', 'Grafana'],
    lastSyncedAt: new Date().toISOString(),
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-2',
    slug: 'cloud-native-api-gateway',
    githubRepoId: 80102145,
    githubName: 'cloud-native-api-gateway',
    githubFullName: 'lakviruperera/cloud-native-api-gateway',
    githubUrl: 'https://github.com/lakviruperera/cloud-native-api-gateway',
    githubDescription: 'Resilient API Gateway featuring dynamic upstream routing, token bucket rate-limiting, JWT authentication middleware, and automated circuit breaking.',
    githubStars: 98,
    githubForks: 19,
    githubLanguage: 'TypeScript',
    githubLanguages: ['TypeScript', 'Node.js', 'Docker', 'Shell'],
    githubTopics: ['api-gateway', 'rate-limiting', 'circuit-breaker', 'security', 'docker', 'devops'],
    githubReadme: `# Cloud-Native API Gateway\n\nHigh-performance reverse proxy and API routing layer with distributed rate limiting and fault tolerance mechanisms.`,
    githubCreatedAt: '2024-05-18T14:20:00Z',
    githubUpdatedAt: '2025-02-10T09:15:00Z',
    customTitle: 'Cloud-Native API Gateway & Service Mesh',
    customDescription: 'A modular, high-performance API gateway engineered for microservices, featuring Redis-backed token bucket rate limiting, automated mTLS encryption, and distributed circuit breakers.',
    category: 'Cloud/DevOps',
    status: 'FEATURED',
    isFeatured: true,
    isVisible: true,
    displayOrder: 2,
    thumbnail: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1200&q=80',
    screenshots: [
      'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80'
    ],
    problem: 'Microservice ecosystems lacked a unified entry point for authorization, traffic throttling, request validation, and observable request tracing, causing repetitive boilerplate in downstream services.',
    solution: 'Engineered a unified gateway layer with asynchronous non-blocking request pipelines, distributed sliding-window rate limiters, and automated circuit breakers preventing cascading service failure.',
    myRole: 'Backend Engineer — Developed core middleware pipelines, Redis cluster integration, and automated CI/CD deployment charts.',
    features: [
      'Distributed sliding window & token bucket rate limiting per API key',
      'Automated circuit breaking with configurable error thresholds and health recovery',
      'Zero-downtime hot reloading of upstream route configurations',
      'OpenTelemetry distributed tracing injection into HTTP headers'
    ],
    demoUrl: 'https://gateway-demo.lakviru.dev',
    architecture: 'Edge Ingress → Gateway Core Middleware → Token Auth & Rate Limiter → Circuit Breaker → Downstream Microservice Fleet',
    technologies: ['TypeScript', 'Node.js', 'Express.js', 'Redis', 'Docker', 'OpenTelemetry', 'PostgreSQL'],
    lastSyncedAt: new Date().toISOString(),
    createdAt: '2024-05-18T14:20:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-3',
    slug: 'realtime-collaborative-workspace',
    githubRepoId: 80102146,
    githubName: 'realtime-collaborative-workspace',
    githubFullName: 'lakviruperera/realtime-collaborative-workspace',
    githubUrl: 'https://github.com/lakviruperera/realtime-collaborative-workspace',
    githubDescription: 'Full-stack collaborative engineering document editor powered by CRDTs (Conflict-free Replicated Data Types), WebSockets, Next.js, and PostgreSQL.',
    githubStars: 115,
    githubForks: 22,
    githubLanguage: 'TypeScript',
    githubLanguages: ['TypeScript', 'React', 'Tailwind CSS', 'PostgreSQL'],
    githubTopics: ['crdt', 'yjs', 'websockets', 'nextjs', 'react', 'collaboration', 'fullstack'],
    githubReadme: `# Real-Time Collaborative Workspace\n\nA modern multi-player document and diagramming canvas for software engineering teams.`,
    githubCreatedAt: '2024-07-02T11:45:00Z',
    githubUpdatedAt: '2025-02-20T16:00:00Z',
    customTitle: 'Real-Time Collaborative Engineering Workspace',
    customDescription: 'A multi-user collaborative workspace and technical documentation editor using Yjs CRDTs, WebSocket rooms, presence awareness, and live syntax-highlighted code blocks.',
    category: 'Full-Stack',
    status: 'FEATURED',
    isFeatured: true,
    isVisible: true,
    displayOrder: 3,
    thumbnail: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    screenshots: [
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80'
    ],
    problem: 'Engineering teams struggled with laggy document syncing and document merge conflicts when drafting technical specifications simultaneously.',
    solution: 'Implemented peer-to-peer and client-server synchronization using Yjs CRDT algorithms, ensuring conflict-free merges, offline editing capabilities, and real-time live cursor presence.',
    myRole: 'Full Stack Engineer — Built the frontend canvas interface with Next.js, developed WebSocket cluster rooms, and integrated PostgreSQL storage backups.',
    features: [
      'Conflict-free real-time concurrent editing with Yjs and WebSockets',
      'Live multiplayer cursor positions, user presence, and selection highlights',
      'Interactive Markdown & Mermaid diagram rendering engine',
      'Snapshot version history with full rollback capabilities'
    ],
    demoUrl: 'https://collab-workspace.lakviru.dev',
    architecture: 'Next.js App Router UI → WebSocket Connection Broker → CRDT State Engine → PostgreSQL Snapshot Store',
    technologies: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'WebSockets', 'PostgreSQL', 'Prisma'],
    lastSyncedAt: new Date().toISOString(),
    createdAt: '2024-07-02T11:45:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-4',
    slug: 'neural-rag-knowledge-search',
    githubRepoId: 80102147,
    githubName: 'neural-rag-search',
    githubFullName: 'lakviruperera/neural-rag-search',
    githubUrl: 'https://github.com/lakviruperera/neural-rag-search',
    githubDescription: 'Semantic search and Retrieval-Augmented Generation (RAG) pipeline for indexing large-scale technical codebases and documentation using vector embeddings and PostgreSQL pgvector.',
    githubStars: 87,
    githubForks: 14,
    githubLanguage: 'Python',
    githubLanguages: ['Python', 'TypeScript', 'PostgreSQL', 'Docker'],
    githubTopics: ['rag', 'vector-search', 'pgvector', 'python', 'fastapi', 'llm', 'embeddings'],
    githubReadme: `# Neural RAG Knowledge Search\n\nHigh-accuracy retrieval system for source code repositories and technical documents.`,
    githubCreatedAt: '2024-09-14T08:10:00Z',
    githubUpdatedAt: '2025-02-18T12:00:00Z',
    customTitle: 'Neural RAG Codebase Search Engine',
    customDescription: 'An enterprise-grade semantic search engine that ingests large code repositories, breaks code into AST chunks, creates vector embeddings, and enables natural language contextual querying.',
    category: 'Backend',
    status: 'PUBLISHED',
    isFeatured: false,
    isVisible: true,
    displayOrder: 4,
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    screenshots: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80'
    ],
    problem: 'Developers spent excessive time navigating multi-repository monorepos searching for functions, API endpoints, and implementation patterns.',
    solution: 'Built an automated AST parsing and vector ingestion pipeline using Python and pgvector with hybrid BM25 + dense vector ranking for pinpoint search accuracy.',
    myRole: 'Backend Developer — Implemented chunking pipelines, vector indexing with pgvector, and FastAPI query endpoints.',
    features: [
      'Hybrid lexical (BM25) and dense semantic vector search reranking',
      'AST-aware code chunking respecting class and function boundaries',
      'Sub-50ms vector query execution over 500,000 indexed code snippets',
      'Interactive Next.js search UI with code diff viewer'
    ],
    demoUrl: 'https://rag-search.lakviru.dev',
    architecture: 'Git Repo Ingestion → AST Chunker → Embedding Generator → PostgreSQL pgvector DB → FastAPI Query Engine → Next.js Frontend',
    technologies: ['Python', 'FastAPI', 'PostgreSQL', 'TypeScript', 'Next.js', 'Docker'],
    lastSyncedAt: new Date().toISOString(),
    createdAt: '2024-09-14T08:10:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-5',
    slug: 'automated-infra-metrics-monitor',
    githubRepoId: 80102148,
    githubName: 'infra-metrics-monitor',
    githubFullName: 'lakviruperera/infra-metrics-monitor',
    githubUrl: 'https://github.com/lakviruperera/infra-metrics-monitor',
    githubDescription: 'Lightweight, self-hosted infrastructure telemetry agent and real-time dashboard for server CPU, memory, disk I/O, and container health.',
    githubStars: 64,
    githubForks: 11,
    githubLanguage: 'TypeScript',
    githubLanguages: ['TypeScript', 'React', 'Docker', 'Shell'],
    githubTopics: ['devops', 'monitoring', 'telemetry', 'docker', 'metrics', 'linux'],
    githubReadme: `# Infrastructure Metrics Monitor\n\nSelf-hosted system telemetry and container health monitoring daemon.`,
    githubCreatedAt: '2024-11-05T13:00:00Z',
    githubUpdatedAt: '2025-01-28T10:45:00Z',
    customTitle: 'Cloud Infrastructure & Telemetry Monitor',
    customDescription: 'A lightweight server monitoring agent and interactive dashboard providing real-time metrics for Linux hosts, Docker containers, and database performance.',
    category: 'Cloud/DevOps',
    status: 'PUBLISHED',
    isFeatured: false,
    isVisible: true,
    displayOrder: 5,
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    screenshots: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80'
    ],
    problem: 'Small and medium teams needed server and container monitoring without the high overhead and cost of heavy enterprise monitoring suites.',
    solution: 'Created an ultra-lightweight binary agent that streams system stats over WebSocket connections to an intuitive Next.js management portal.',
    myRole: 'DevOps & Full Stack Engineer — Authored the telemetry collector daemon and built the interactive analytics charts.',
    features: [
      'Under 15MB memory footprint on monitored host servers',
      'Real-time CPU, RAM, Network I/O and Docker container metrics streaming',
      'Configurable threshold alerts via Webhook, Slack, and Discord',
      'Historical trend analysis with automated database rollups'
    ],
    demoUrl: 'https://infra-monitor.lakviru.dev',
    architecture: 'Host Agent Daemon → Secure WebSocket Tunnel → Ingestion Engine → Time-series DB → Next.js Dashboard',
    technologies: ['TypeScript', 'Node.js', 'React', 'Next.js', 'Docker', 'Linux', 'Tailwind CSS'],
    lastSyncedAt: new Date().toISOString(),
    createdAt: '2024-11-05T13:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-6',
    slug: 'flutter-mobile-finance-companion',
    githubRepoId: 80102149,
    githubName: 'mobile-finance-companion',
    githubFullName: 'lakviruperera/mobile-finance-companion',
    githubUrl: 'https://github.com/lakviruperera/mobile-finance-companion',
    githubDescription: 'Cross-platform personal finance management mobile application built with Flutter, Dart, SQLite, and Supabase cloud sync.',
    githubStars: 73,
    githubForks: 16,
    githubLanguage: 'Dart',
    githubLanguages: ['Dart', 'Flutter', 'SQL'],
    githubTopics: ['flutter', 'dart', 'mobile-app', 'finance', 'supabase', 'cross-platform'],
    githubReadme: `# Mobile Finance Companion\n\nCross-platform personal finance tracker with offline-first data synchronization.`,
    githubCreatedAt: '2024-06-12T09:00:00Z',
    githubUpdatedAt: '2025-02-05T14:10:00Z',
    customTitle: 'Cross-Platform Financial Tracker Mobile App',
    customDescription: 'An offline-first mobile application for budget tracking, automated expense categorization, interactive charts, and multi-currency exchange conversion.',
    category: 'Mobile',
    status: 'PUBLISHED',
    isFeatured: false,
    isVisible: true,
    displayOrder: 6,
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    screenshots: [
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80'
    ],
    problem: 'Users required a fast, offline-capable mobile budget tracker that securely syncs across devices without exposing banking credentials.',
    solution: 'Developed an offline-first architecture using local SQLite storage with background incremental sync to Supabase PostgreSQL when internet connectivity is detected.',
    myRole: 'Mobile & Backend Developer — Built the Flutter client, custom animations, and backend synchronization logic.',
    features: [
      '100% functional offline with seamless automatic cloud reconciliation',
      'Biometric authentication (FaceID & Fingerprint)',
      'Rich interactive expense breakdown charts and budget forecasts',
      'Exportable financial reports in CSV and PDF formats'
    ],
    demoUrl: 'https://finance-app.lakviru.dev',
    architecture: 'Flutter UI → BLoC State Management → Local SQLite Cache ⇄ Supabase Cloud Sync & Auth',
    technologies: ['Flutter', 'Dart', 'Supabase', 'PostgreSQL', 'SQLite', 'Git'],
    lastSyncedAt: new Date().toISOString(),
    createdAt: '2024-06-12T09:00:00Z',
    updatedAt: new Date().toISOString(),
  }
];

export const INITIAL_SKILLS: SkillData[] = [
  // Languages
  { id: 'sk-1', name: 'TypeScript', category: 'LANGUAGES', skillLevel: 95, icon: 'FileCode', description: 'Advanced type gymnastics, generics, compiler API, and clean architecture', displayOrder: 1, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-2', name: 'JavaScript (ES6+)', category: 'LANGUAGES', skillLevel: 95, icon: 'FileCode2', description: 'Event loop, asynchronous programming, Web APIs, and Node.js runtime', displayOrder: 2, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-3', name: 'Python', category: 'LANGUAGES', skillLevel: 90, icon: 'Terminal', description: 'Backend development, async I/O, data pipelines, and AI/RAG tooling', displayOrder: 3, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-4', name: 'SQL', category: 'LANGUAGES', skillLevel: 92, icon: 'Database', description: 'Complex queries, query optimization, indexing strategies, and schema design', displayOrder: 4, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-5', name: 'Dart', category: 'LANGUAGES', skillLevel: 85, icon: 'Smartphone', description: 'Cross-platform mobile applications, state management, and asynchronous streams', displayOrder: 5, isFeatured: false, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-6', name: 'Java', category: 'LANGUAGES', skillLevel: 80, icon: 'Coffee', description: 'Object-oriented patterns, multithreading, and enterprise backend systems', displayOrder: 6, isFeatured: false, createdAt: '2024-01-01', updatedAt: '2024-01-01' },

  // Frontend
  { id: 'sk-7', name: 'Next.js (App Router)', category: 'FRONTEND', skillLevel: 95, icon: 'Layers', description: 'Server Components, Server Actions, Route Handlers, ISR, SSR, and SEO', displayOrder: 1, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-8', name: 'React', category: 'FRONTEND', skillLevel: 95, icon: 'Atom', description: 'Custom hooks, state management, performance optimization, and concurrent rendering', displayOrder: 2, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-9', name: 'Tailwind CSS', category: 'FRONTEND', skillLevel: 92, icon: 'Palette', description: 'Design systems, responsive UI, glassmorphism, and modern animations', displayOrder: 3, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-10', name: 'Flutter', category: 'FRONTEND', skillLevel: 85, icon: 'Smartphone', description: 'Cross-platform iOS and Android apps, BLoC architecture, and offline caching', displayOrder: 4, isFeatured: false, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-11', name: 'HTML5 & CSS3', category: 'FRONTEND', skillLevel: 95, icon: 'Code', description: 'Semantic HTML, accessibility (a11y), CSS variables, and layout engines', displayOrder: 5, isFeatured: false, createdAt: '2024-01-01', updatedAt: '2024-01-01' },

  // Backend
  { id: 'sk-12', name: 'Node.js', category: 'BACKEND', skillLevel: 92, icon: 'Server', description: 'Event-driven backend services, streaming I/O, worker threads, and microservices', displayOrder: 1, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-13', name: 'Express.js', category: 'BACKEND', skillLevel: 90, icon: 'Cpu', description: 'RESTful API architecture, middleware security, and authentication pipelines', displayOrder: 2, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-14', name: 'REST APIs & GraphQL', category: 'BACKEND', skillLevel: 92, icon: 'Network', description: 'API contract design, rate-limiting, documentation, and schema stitching', displayOrder: 3, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-15', name: 'FastAPI / Python Backend', category: 'BACKEND', skillLevel: 88, icon: 'Zap', description: 'High-performance asynchronous Python microservices and vector pipelines', displayOrder: 4, isFeatured: false, createdAt: '2024-01-01', updatedAt: '2024-01-01' },

  // Databases
  { id: 'sk-16', name: 'PostgreSQL & Prisma', category: 'DATABASES', skillLevel: 92, icon: 'Database', description: 'Relational data modeling, ACID transactions, migrations, and performance tuning', displayOrder: 1, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-17', name: 'MongoDB', category: 'DATABASES', skillLevel: 85, icon: 'FolderTree', description: 'Document stores, aggregation pipelines, and sharding strategies', displayOrder: 2, isFeatured: false, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-18', name: 'Supabase', category: 'DATABASES', skillLevel: 90, icon: 'ShieldCheck', description: 'Row-Level Security (RLS), real-time subscriptions, and Edge Functions', displayOrder: 3, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-19', name: 'Redis', category: 'DATABASES', skillLevel: 88, icon: 'Boxes', description: 'In-memory caching, distributed locks, session management, and pub/sub', displayOrder: 4, isFeatured: false, createdAt: '2024-01-01', updatedAt: '2024-01-01' },

  // DevOps / Cloud
  { id: 'sk-20', name: 'Docker & Containers', category: 'DEVOPS_CLOUD', skillLevel: 90, icon: 'Box', description: 'Multi-stage builds, container orchestration, and isolated dev environments', displayOrder: 1, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-21', name: 'Linux / Unix Systems', category: 'DEVOPS_CLOUD', skillLevel: 88, icon: 'TerminalSquare', description: 'Shell scripting, server administration, permissions, and network troubleshooting', displayOrder: 2, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-22', name: 'Git & GitHub Actions CI/CD', category: 'DEVOPS_CLOUD', skillLevel: 94, icon: 'GitBranch', description: 'Automated test runners, release pipelines, linting checks, and cloud deployments', displayOrder: 3, isFeatured: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
  { id: 'sk-23', name: 'Cloud Platforms (Vercel, AWS)', category: 'DEVOPS_CLOUD', skillLevel: 85, icon: 'Cloud', description: 'Serverless deployment, edge caching, IAM policies, and infrastructure monitoring', displayOrder: 4, isFeatured: false, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
];

export const INITIAL_EXPERIENCES: ExperienceData[] = [
  {
    id: 'exp-1',
    company: 'VVH Solutions',
    position: 'Software Engineering Intern',
    location: 'Piliyandala, Sri Lanka',
    startDate: '2026-01-02',
    endDate: '2026-07-10',
    isCurrent: false,
    description: '',
    responsibilities: [
      'Integrated UI/UX designs into responsive and functional frontend interfaces.',
      'Contributed to Flutter mobile application development and implementation of application features.',
      'Integrated Firebase services into mobile applications where required.',
      'Worked with Docker for containerized application development and environment management.',
      'Contributed to Server-Sent Events (SSE) integration to support real-time data updates and communication.',
      'Collaborated on frontend and mobile application development tasks and contributed to the implementation of software features.',
    ],
    achievements: [],
    technologies: ['Flutter', 'Firebase', 'Docker', 'Server-Sent Events (SSE)', 'Frontend UI/UX'],
    displayOrder: 1,
    createdAt: '2026-01-02',
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_EDUCATIONS: EducationData[] = [
  {
    id: 'edu-1',
    institution: 'Sri Lanka Institute of Information Technology (SLIIT)',
    degree: 'BSc (Hons) in Information Technology',
    field: 'Software Engineering',
    location: 'Malabe, Sri Lanka',
    startDate: '2023',
    endDate: 'Present',
    isCurrent: true,
    description: '',
    grade: '',
    displayOrder: 1,
    createdAt: '2023-01-01',
    updatedAt: new Date().toISOString(),
  },
];
